site_name: Tech writer toolkit
site_description: Tools and resources for tech writers.
site_author: Deborah Barnard
site_url: https://techwritertoolkit.com/
repo_name: 'StarfallProjects/tech-writer-toolkit'
repo_url: 'https://github.com/StarfallProjects/tech-writer-toolkit'
theme:
  name: 'material'
  custom_dir: customTheme
  favicon: assets/images/school.ico
  icon:
    logo: material/school
  language: 'en'
  palette:
    primary: 'purple'
    accent: 'purple'
  features:
    - tabs
google_analytics:
  - 'UA-112380159-4'
  - 'auto'
markdown_extensions:
  - admonition
  - pymdownx.highlight:
      use_pygments: true
  - toc:
      permalink: "#"
nav:
  - Home: index.md
  - Consulting and freelancing:
    - Introduction: consultant/introduction.md
    - Core values and first thoughts: consultant/core-values.md
    - Business identity: consultant/business-identity.md
    - Business plan: consultant/business-plan.md
    - Project planning: consultant/project-planning.md
    - Cost estimate: consultant/cost-estimate.md
    - One page contract: consultant/one-page-contract.md
    - Workflow: consultant/workflow.md
    - Finding work: consultant/find-work.md
    - Getting paid: consultant/get-paid.md
  - Links and resources: 
    - Introduction: resources/introduction.md
    - Reading list: resources/reading-list.md
    - Tools: resources/tools.md
    - Tax: resources/tax-links.md
  - About: about.md
